### model
model_name_or_path: /inspire/hdd/global_user/liupengfei-24025/rzfan/models/Qwen2.5-3B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
flash_attn: fa2

### dataset
dataset: megascience_mixture_filtering
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 64
template: qwen

### output
output_dir: /inspire/hdd/global_user/liupengfei-24025/rzfan/models/science_sft/qwen2.5-3B/megascience_mixture_filtering.lr5e-6.bs512-epoch-3
logging_steps: 1
save_strategy: epoch
# save_steps: 1000
plot_loss: true
overwrite_output_dir: true
report_to: wandb

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 5.0e-6
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000